### ISSUE TITLE
db.getItem in combination with db.setSchema()

### ISSUE THREAD

**Issue by sbat** [epha/dynamo#10]
If i will use ```db.getItem()``` ...

```
        return db.getItem({ TableName: "resource", Key: { id: { S: id } } })
            .then(function(res) {
                return res.Item;
            });
```

... and call ```db.setSchema()``` bevor i get this error:

```
ValidationException: Invalid attribute value type
    at Request.extractError (policy/node_modules/dynamo/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (policy/node_modules/dynamo/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (policy/node_modules/dynamo/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (policy/node_modules/dynamo/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (policy/node_modules/dynamo/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (policy/node_modules/dynamo/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at policy/node_modules/dynamo/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (policy/node_modules/dynamo/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (policy/node_modules/dynamo/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (policy/node_modules/dynamo/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

**Comment by meaku** [comment]
ids are automatically converted atm. Its just not streamlined on all method. 

Try:

return db.getItem({ TableName: "resource", Key: { id: id }  })

**Comment by meaku** [comment]
Just call db.transform = null to enable raw mode without transformation. You'll have to do the transfomation yourself then, but it might help experimenting with errors.
